### ISSUE TITLE
Sub: Label arming checks that are not usually used by ROVs

### ISSUE THREAD

**Issue by dheideman** [bluerobotics/qgroundcontrol#76]
Some arming checks on the Safety page are UAV-specific.  Label these as such so users aren't afraid to disable non-essential checks.

**Comment by jaxxzer** [comment]
What we need to do is remove them entirely. The root cause of these appearing is the parameter metadata parsing script in the ardupilot repository. These parameters are shared between vehicles, so unless we make that script more sophisticated, the way to remove these options is to manually remove the offending enum entries from the parameter metadata file.

**Comment by jaxxzer** [comment]
Upstream pr: https://github.com/mavlink/qgroundcontrol/pull/6399
